// <auto-generated />
using System;
using Aqi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aqi.Migrations
{
    [DbContext(typeof(AqiDbContext))]
    partial class AqiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aqi.Models.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountryIdCountry")
                        .HasColumnType("int");

                    b.Property<int>("LocationIdLocation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("IdCity");

                    b.HasIndex("CountryIdCountry");

                    b.HasIndex("LocationIdLocation");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Aqi.Models.Country", b =>
                {
                    b.Property<int>("IdCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(3) CHARACTER SET utf8mb4")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("IdCountry");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Aqi.Models.Location", b =>
                {
                    b.Property<int>("IdLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Accuracy")
                        .HasColumnType("double");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.HasKey("IdLocation");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Aqi.Models.Measurement", b =>
                {
                    b.Property<int>("IdMeasurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<int>("StationFK")
                        .HasColumnType("int");

                    b.Property<int?>("StationIdStation")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("IdMeasurement");

                    b.HasIndex("StationIdStation");

                    b.ToTable("Measurement");
                });

            modelBuilder.Entity("Aqi.Models.Station", b =>
                {
                    b.Property<int>("IdStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityIdCity")
                        .HasColumnType("int");

                    b.Property<int>("CountryIdCountry")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LocationIdLocation")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("IdStation");

                    b.HasIndex("CityIdCity");

                    b.HasIndex("CountryIdCountry");

                    b.HasIndex("LocationIdLocation");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Aqi.Models.City", b =>
                {
                    b.HasOne("Aqi.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryIdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aqi.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationIdLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aqi.Models.Measurement", b =>
                {
                    b.HasOne("Aqi.Models.Station", null)
                        .WithMany("Measurements")
                        .HasForeignKey("StationIdStation");
                });

            modelBuilder.Entity("Aqi.Models.Station", b =>
                {
                    b.HasOne("Aqi.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityIdCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aqi.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryIdCountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aqi.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationIdLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
